ALTER TABLE users
    ADD COLUMN IF NOT EXISTS total_gifted DECIMAL(20,8) NOT NULL DEFAULT 0;

ALTER TABLE redeem_codes
    ADD COLUMN IF NOT EXISTS balance_source VARCHAR(20) NOT NULL DEFAULT 'paid';
